/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzeriadechela;

/**
 *
 * @author Anaiza
 */
public class AdminClientesJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminClientesJFrame
     */
    public AdminClientesJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void limpiar(){
        _dniTextField.setText("");
        _nombresTextField.setText("");
        _apellidoPTextField.setText("");
        _apellidoMTextField.setText("");
        _distritoTextField.setText("");
        _direccionTextField.setText("");
        _celularTextField.setText("");
        _contraTextField.setText("");
    }
    
    public String getDni(){
        return _dniTextField.getText();
    }
    
    public String getNombres(){
        return _nombresTextField.getText();
    }
    
    public String getApellidoP(){
        return _apellidoPTextField.getText();
    }
    
    public String getApellidoM(){
        return _apellidoMTextField.getText();
    }
    
    public String getDistrito(){
        return _distritoTextField.getText();
    }
    
    public String getDireccion(){
        return _direccionTextField.getText();
    }
    
    public String getCelular(){
        return _celularTextField.getText();
    }
    
    public String getContrasena(){
        return new String(_contraTextField.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _distritoTextField = new javax.swing.JTextField();
        _celularTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        _dniTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        _nombresTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        _apellidoMTextField = new javax.swing.JTextField();
        _apellidoPTextField = new javax.swing.JTextField();
        _direccionTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        _contraTextField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        _distritoTextField.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        getContentPane().add(_distritoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 190, 30));

        _celularTextField.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        getContentPane().add(_celularTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 190, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Celular:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("DNI:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, 30));

        _dniTextField.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        getContentPane().add(_dniTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 190, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Nombres:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 30));

        _nombresTextField.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        getContentPane().add(_nombresTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 190, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Apellido Paterno:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        _apellidoMTextField.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        getContentPane().add(_apellidoMTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 190, 30));

        _apellidoPTextField.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        getContentPane().add(_apellidoPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 190, 30));

        _direccionTextField.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        getContentPane().add(_direccionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 190, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Apellido Materno:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Dirección:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Distrito:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Contraseña:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, 30));

        _contraTextField.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        _contraTextField.setMaximumSize(new java.awt.Dimension(4, 20));
        getContentPane().add(_contraTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 190, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/0.1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminClientesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminClientesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminClientesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminClientesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminClientesJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField _apellidoMTextField;
    private javax.swing.JTextField _apellidoPTextField;
    private javax.swing.JTextField _celularTextField;
    private javax.swing.JPasswordField _contraTextField;
    private javax.swing.JTextField _direccionTextField;
    private javax.swing.JTextField _distritoTextField;
    private javax.swing.JTextField _dniTextField;
    private javax.swing.JTextField _nombresTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
