/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzeriadechela;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import pizzeriadechela.database.MysqlAction;
import pizzeriadechela.database.data.*;
import pizzeriadechela.componentes.*;

/**
 *
 * @author Anaiza
 */
public class PizzeriaDChelaFrame extends javax.swing.JFrame {
    
    private javax.swing.JFrame _principal;
    private Boolean _cargado;
    private Boolean _isPizzasView;
    
    // Puede ser cliente o trabajador
    private CuentaDto _cuenta;
    
    private MysqlAction _mysqlAction;
    
    private ArrayList<PizzasDto> _pizzas;
    private DefaultListModel _modeloLista;
    private DefaultListModel _pedidosLista;
    
    private AdminJFrame _adminFrame;
    
    int getIndexPizza(PizzasDto dto){
        for (int index = 0; index < _modeloLista.size(); index++){
            PizzasDto pizza = (PizzasDto)_modeloLista.get(index);
            if (pizza.toString().equals(dto.toString()))
                return index;
        }
        return -1;
    }
    
    PizzasDto getPizzaByIndex(int index){
        if (index < 0)
            return null;
        
        return (PizzasDto)_modeloLista.get(index);
    }
    
    int getIndexPedido(PedidosDto dto){
        for (int index = 0; index < _modeloLista.size(); index++){
            PedidosDto pedido = (PedidosDto)_pedidosLista.get(index);
            if (pedido.toString().equals(dto.toString()))
                return index;
        }
        return -1;
    }
    
    PedidosDto getPedidoByIndex(int index){
        if (index < 0)
            return null;
        
        return (PedidosDto)_pedidosLista.get(index);
    }
    
    /*void addElement(Object o){
        _modeloLista.addElement(o);
        _pizzasJList.setModel(_modeloLista);
        _pizzasJList.updateUI();
    }
    
    void updateElement(Object o){
        int index = getIndexPizza((PizzasDto)o);
        if (index < 0)
            return;
        
        _modeloLista.setElementAt(o, index);
        _pizzasJList.setModel(_modeloLista);
        _pizzasJList.updateUI();
    }
    
    void removeElement(Object o){
        int index = getIndexPizza((PizzasDto)o);
        if (index < 0)
            return;
        
        _modeloLista.removeElementAt(index);
        _pizzasJList.setModel(_modeloLista);
        _pizzasJList.updateUI();
    }*/

    /**
     * Creates new form PizzeriaDChelaFrame
     */
    
    void restablecerOrdenView(){
        _pizzaImgPanel.removeAll();
        _pizzaImgPanel.repaint();
        _precioLabel.setText("Precio");
        _metodopagoComboBox.setSelectedIndex(-1);
        _cantidadTextField.setText("1");
    }
    
    public PizzeriaDChelaFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public PizzeriaDChelaFrame initializate(javax.swing.JFrame principal, CuentaDto cuenta, MysqlAction mysqlAction){
        _principal = principal;
        _cuenta = cuenta;
        _mysqlAction = mysqlAction;
        _cargado = false;
        _modeloLista = new DefaultListModel();
        _pedidosLista = new DefaultListModel();
        _aminMenuBar.setEnabled(_cuenta.getCargo() > 1);
        return this;
    }
    
    void updatePizzaView(PizzasDto pizza){

        Imagen imagen = new Imagen(284, 141);
        imagen.setImageUrl(pizza.getImagenUrl());
        _pizzaImgPanel.add(imagen);
        _pizzaImgPanel.repaint();
        
        JOptionPane.showMessageDialog(null, String.format("Nombre: %s\nDescripcion: %s\nPrecio: %10.2f\nOferta: %s",
                pizza.getNombre(), pizza.getDescripcion(), pizza.getPrecio(), pizza.getOferta() == 1 ? "2X1" : "No"),
                "Informacion de la Pizza", JOptionPane.INFORMATION_MESSAGE);
        
        _precioLabel.setText(String.format("S/%10.2f", pizza.getPrecio()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        _pizzasJList = new javax.swing.JList();
        _pizzaImgPanel = new javax.swing.JPanel();
        _cancelarJButton = new javax.swing.JButton();
        _seleccionarJButton = new javax.swing.JButton();
        _ordenarJButton = new javax.swing.JButton();
        _precioLabel = new javax.swing.JLabel();
        _dniTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        _cantidadTextField = new javax.swing.JTextField();
        _pedidosButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        _metodopagoComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        _verPizzasMenuBar = new javax.swing.JMenu();
        _aminMenuBar = new javax.swing.JMenu();
        _cerrarSessionMenuBar = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        _pizzasJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(_pizzasJList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 240, 410));

        javax.swing.GroupLayout _pizzaImgPanelLayout = new javax.swing.GroupLayout(_pizzaImgPanel);
        _pizzaImgPanel.setLayout(_pizzaImgPanelLayout);
        _pizzaImgPanelLayout.setHorizontalGroup(
            _pizzaImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        _pizzaImgPanelLayout.setVerticalGroup(
            _pizzaImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        getContentPane().add(_pizzaImgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 250, 150));

        _cancelarJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        _cancelarJButton.setText("Cancelar");
        _cancelarJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _cancelarJButtonMouseClicked(evt);
            }
        });
        getContentPane().add(_cancelarJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, -1, -1));

        _seleccionarJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _seleccionarJButton.setText("Seleccionar");
        _seleccionarJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _seleccionarJButtonMouseClicked(evt);
            }
        });
        getContentPane().add(_seleccionarJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        _ordenarJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        _ordenarJButton.setText("Ordenar");
        _ordenarJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _ordenarJButtonMouseClicked(evt);
            }
        });
        getContentPane().add(_ordenarJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, -1, -1));

        _precioLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        _precioLabel.setText("Precio");
        getContentPane().add(_precioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, 30));

        _dniTextField.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        getContentPane().add(_dniTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 180, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setText("Cantidad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, 30));

        _cantidadTextField.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        _cantidadTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _cantidadTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(_cantidadTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 180, 30));

        _pedidosButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        _pedidosButton.setText("Pedidos");
        _pedidosButton.setToolTipText("");
        _pedidosButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _pedidosButtonMouseClicked(evt);
            }
        });
        getContentPane().add(_pedidosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel4.setText("Cliente DNI:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel5.setText("Metodo Pago:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, 30));

        _metodopagoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Visa", "Transferencia - Yape" }));
        _metodopagoComboBox.setSelectedIndex(-1);
        getContentPane().add(_metodopagoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/0.1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 102)));

        jMenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenu2.setText("Menu");

        _verPizzasMenuBar.setText("Ver Pizzas");
        _verPizzasMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _verPizzasMenuBarMouseClicked(evt);
            }
        });
        jMenu2.add(_verPizzasMenuBar);

        jMenuBar1.add(jMenu2);

        _aminMenuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        _aminMenuBar.setText("Admin");
        _aminMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _aminMenuBarMouseClicked(evt);
            }
        });
        jMenuBar1.add(_aminMenuBar);

        _cerrarSessionMenuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        _cerrarSessionMenuBar.setText("Cerrar Sesión");
        _cerrarSessionMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _cerrarSessionMenuBarMouseClicked(evt);
            }
        });
        jMenuBar1.add(_cerrarSessionMenuBar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if (!_cargado){
            _pizzas = _mysqlAction.getPizzas();
            for (int i = 0; i < _pizzas.size(); i++){
                _modeloLista.addElement(_pizzas.get(i));
            }
            _pizzasJList.setModel(_modeloLista);
            _pizzasJList.updateUI();
            _isPizzasView = true;
            _cargado = true;
        }
    }//GEN-LAST:event_formWindowActivated

    private void _seleccionarJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__seleccionarJButtonMouseClicked
        // TODO add your handling code here:
        if (_isPizzasView){
            PizzasDto pizza = getPizzaByIndex(_pizzasJList.getSelectedIndex());
            if (pizza == null){
                JOptionPane.showMessageDialog(null, "No se ha seleccionado una pizza.", "Ocurrio un error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            updatePizzaView(pizza);
        }else{
            PedidosDto pedido = getPedidoByIndex(_pizzasJList.getSelectedIndex());
            if (pedido == null){
                    return;
                }
            JOptionPane.showMessageDialog(null, String.format("Cliente DNI: %s\nNombre: %s\nTamaño: %s\nMetodo de Pago: %s\nFecha: %s\nCantidad: %d",
                pedido.getDniC(), pedido.getDetalle().getPizzas().getNombre(), pedido.getDetalle().getTamanio(),
                pedido.getDetalle().getMetodoPago() == 0 ? "Visa" : "Transferencia Yape", pedido.getComprobante().getFecha(),
                pedido.getDetalle().getCantidad()),
                "Informacion del Pedido", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event__seleccionarJButtonMouseClicked

    private void _verPizzasMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__verPizzasMenuBarMouseClicked
        // TODO add your handling code here:
            restablecerOrdenView();
            _modeloLista.clear();
            _pizzas = _mysqlAction.getPizzas();
            for (int i = 0; i < _pizzas.size(); i++){
                _modeloLista.addElement(_pizzas.get(i));
            }
            _pizzasJList.setModel(_modeloLista);
            _pizzasJList.updateUI();
            _isPizzasView = true;
    }//GEN-LAST:event__verPizzasMenuBarMouseClicked

    private void _cerrarSessionMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__cerrarSessionMenuBarMouseClicked
        // TODO add your handling code here:
        
        if (_adminFrame != null){
            _adminFrame.dispose();
        }
        
        _principal.setVisible(true);
        dispose();
    }//GEN-LAST:event__cerrarSessionMenuBarMouseClicked

    private void _aminMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__aminMenuBarMouseClicked
        // TODO add your handling code here:
        if (_adminFrame != null){
            _adminFrame.setFocusable(true);
            return;
        }
        
        _adminFrame = new AdminJFrame();
        _adminFrame.initializate(_mysqlAction, this);
            _adminFrame.setVisible(true);
    }//GEN-LAST:event__aminMenuBarMouseClicked

    private void _pedidosButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__pedidosButtonMouseClicked
        // TODO add your handling code here:
        
        if (!Utilidad.validarDNI(_dniTextField.getText())){
            JOptionPane.showMessageDialog(null, "El DNI del cliente no es válido.", "Ocurrio un error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        _pedidosLista.clear();
        ArrayList<PedidosDto> pedidos = _mysqlAction.getPedidos(_dniTextField.getText(), _cuenta.getDni());
        if (pedidos.size() < 1){
            JOptionPane.showMessageDialog(null, "No se encontraron pedidos del cliente.", "Ocurrio un error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        for (int index = 0; index < pedidos.size(); index++){
            _pedidosLista.addElement(pedidos.get(index));
        }
        _pizzasJList.setModel(_pedidosLista);
        _pizzasJList.updateUI();
        _isPizzasView = false;
        
    }//GEN-LAST:event__pedidosButtonMouseClicked

    private void _ordenarJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__ordenarJButtonMouseClicked
        // TODO add your handling code here:
        
        if (!_isPizzasView){
            return;
        }
        
        if (!Utilidad.validarDNI(_dniTextField.getText())){
            JOptionPane.showMessageDialog(null, "El DNI del cliente no es válido.", "Ocurrio un error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (_metodopagoComboBox.getSelectedIndex() < 0){
            JOptionPane.showMessageDialog(null, "El Metodo de Pago no es válido.", "Ocurrio un error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!Utilidad.validarCantidad(_cantidadTextField.getText())){
            JOptionPane.showMessageDialog(null, "La cantidad no es válido.", "Ocurrio un error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        PizzasDto pizza = getPizzaByIndex(_pizzasJList.getSelectedIndex());
        if (pizza == null){
            JOptionPane.showMessageDialog(null, "No se ha seleccionado una pizza.", "Ocurrio un error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        PedidosDto pedidos = new PedidosDto();
        pedidos.setDniC(_dniTextField.getText());
        pedidos.setDniV(_cuenta.getDni());
        pedidos.setDetalle(new PizzaDetalleDto());
        pedidos.getDetalle().setPizzaId(pizza.getId());
        pedidos.getDetalle().setMetodoPago((byte)_metodopagoComboBox.getSelectedIndex());
        pedidos.getDetalle().setTamanio(pizza.getDescripcion());
        pedidos.getDetalle().setCantidad(Utilidad.toByte(_cantidadTextField.getText()));
        
        if (!_mysqlAction.addPedido(pedidos)){
            JOptionPane.showMessageDialog(null, "No se pudo ordenar el pedido.", "Ocurrio un error", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Se ha ordenado el pedido correctamente.", "Ocurrio un error", JOptionPane.INFORMATION_MESSAGE);
            restablecerOrdenView();
        }
    }//GEN-LAST:event__ordenarJButtonMouseClicked

    private void _cancelarJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__cancelarJButtonMouseClicked
        // TODO add your handling code here:
        if (!_isPizzasView){
            PedidosDto pedido = getPedidoByIndex(_pizzasJList.getSelectedIndex());
            if (pedido == null){
                    JOptionPane.showMessageDialog(null, "No se ha seleccionado un pedido.", "Ocurrio un error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            
            if (!_mysqlAction.deletePedido(pedido)){
                JOptionPane.showMessageDialog(null, "No se pudo eliminar el pedido.", "Ocurrio un error", JOptionPane.ERROR_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Pedido eliminado correctamente.", "Ocurrio un error", JOptionPane.INFORMATION_MESSAGE);
                _pedidosLista.remove(_pizzasJList.getSelectedIndex());
                _pizzasJList.setModel(_pedidosLista);
                _pizzasJList.updateUI();
            }
        }else{
            int resultado = JOptionPane.showConfirmDialog(null, "¿Desea restablecer los datos?.", "Ocurrio un error", 1, JOptionPane.INFORMATION_MESSAGE);
            if (resultado == 0){
                restablecerOrdenView();
            }
        }
    }//GEN-LAST:event__cancelarJButtonMouseClicked

    private void _cantidadTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__cantidadTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__cantidadTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzeriaDChelaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzeriaDChelaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzeriaDChelaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzeriaDChelaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzeriaDChelaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu _aminMenuBar;
    private javax.swing.JButton _cancelarJButton;
    private javax.swing.JTextField _cantidadTextField;
    private javax.swing.JMenu _cerrarSessionMenuBar;
    private javax.swing.JTextField _dniTextField;
    private javax.swing.JComboBox _metodopagoComboBox;
    private javax.swing.JButton _ordenarJButton;
    private javax.swing.JButton _pedidosButton;
    private javax.swing.JPanel _pizzaImgPanel;
    private javax.swing.JList _pizzasJList;
    private javax.swing.JLabel _precioLabel;
    private javax.swing.JButton _seleccionarJButton;
    private javax.swing.JMenu _verPizzasMenuBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
